remote_theme: "owasp/www--site-theme"
plugins:
 - jekyll-include-cache-0.2.0
 - jekyll-multiple-languages-plugin
  

# The all languages used
languages:          ['en']

# If not config, the first item of languages will be used as the default.
language_default:   'en'

languageNames:
  de: Deutsch
  en: English